### ISSUE TITLE
Test a fresh project on CI as well

### ISSUE THREAD

**Issue by ariejan** [kabisa/maji#238]
IMHO we should add a test (to `bin/ci`?) that creates a blank Maji app and runs the test on the generated app. This ensures that new users generate an app with passing tests.

I created this issue based on #237.

**Comment by pascalw** [comment]
@ariejan we actually have this already :-)

There is one issue though; the dependencies of the project we generate are not completely locked. We don't use exact versions in the `package.json`, nor include a `yarn.lock`. I think this is fine, because you then always get the latest minor versions of all dependencies, BUT it does mean that the generated project can break when dependencies change.

To prevent this, we could run the test suite nightly. I'll make that change.

**Comment by pascalw** [comment]
Nightly build configured.
