### ISSUE TITLE
non-existing cordova.js causes 404 error in browser 

### ISSUE THREAD

**Issue by bazzel** [kabisa/maji#83]
When a maji app. is run in a web browser (non-native mode), the console shows an error stating that a 404 Not Found occurs, due to a non-existing cordova.js which is only included when a native version of the app. is created.

**Comment by pascalw** [comment]
@bazzel this is true but I don't really see a problem with this. `public/index.html` is now a simple static file. If we wan't to prevent this we would have to add something to build tooling to conditionally add the `cordova.js` script tag, or have Cordova inject `cordova.js` via some plugin but tbh I really don't think that's worth it. Feel free to reopen if you think otherwise.
